### ISSUE TITLE
Installation Issue on Raspberrypi OS

### ISSUE THREAD

**Issue by pranavjandial123** [zaneb/sblim-sfcb#1]
Hi,
I was trying to install sblim-sfcb on Raspberrypi OS. As a pre-requisite, i had to install sblim-sfcCommon and it's giving me an error.

<<<<<
make  all-recursive
make[1]: Entering directory '/home/pi/Downloads/sblim-sfcCommon-1.0.1_old'
Making all in .
make[2]: Entering directory '/home/pi/Downloads/sblim-sfcCommon-1.0.1_old'
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -DLIBDIR=\"/usr/local/lib\"    -g -O2 -MT utilTypeCk.lo -MD -MP -MF .deps/utilTypeCk.Tpo -c -o utilTypeCk.lo `test -f 'sfcUtil/utilTypeCk.c' || echo './'`sfcUtil/utilTypeCk.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -DLIBDIR=\"/usr/local/lib\" -g -O2 -MT utilTypeCk.lo -MD -MP -MF .deps/utilTypeCk.Tpo -c sfcUtil/utilTypeCk.c  -fPIC -DPIC -o .libs/utilTypeCk.o
./libtool: line 983: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8)
In file included from sfcUtil/cmpi/cmpidt.h:48:0,
                 from sfcUtil/utilTypeCk.c:26:
sfcUtil/cmpi/cmpipl.h:36:8: error: #error "You have not defined the right platform. The choices are:"
 **#      error "You have not defined the right platform. The choices are:"**
        ^
sfcUtil/cmpi/cmpipl.h:37:8: error: **#error "CMPI_PLATFORM_LINUX_GENERIC_GNU, CMPI_PLATFORM_HPUX_ACC,"**
 #      error "CMPI_PLATFORM_LINUX_GENERIC_GNU, CMPI_PLATFORM_HPUX_ACC,"
        ^
sfcUtil/cmpi/cmpipl.h:38:8: error: #error "CMPI_PLATFORM_WIN32_IX86_MSVC, CMPI_PLATFORM_SOLARIS_SPARC_GNU,"
 #      error "CMPI_PLATFORM_WIN32_IX86_MSVC, CMPI_PLATFORM_SOLARIS_SPARC_GNU,"
        ^
sfcUtil/cmpi/cmpipl.h:39:8: error: #error "CMPI_PLATFORM_SOLARIS_SPARC_CC, CMPI_PLATFORM_AIX_RS_IBMCXX,"
 #      error "CMPI_PLATFORM_SOLARIS_SPARC_CC, CMPI_PLATFORM_AIX_RS_IBMCXX,"
        ^
sfcUtil/cmpi/cmpipl.h:40:8: error: #error "CMPI_PLATFORM_ZOS_ZSERIES_IBM, CMPI_PLATFORM_TRU64_ALPHA_DECCXX,"
 #      error "CMPI_PLATFORM_ZOS_ZSERIES_IBM, CMPI_PLATFORM_TRU64_ALPHA_DECCXX,"
        ^
sfcUtil/cmpi/cmpipl.h:41:8: error: #error "CMPI_PLATFORM_OS400_ISERIES_IBM, CMPI_PLATFORM_DARWIN_PPC_GNU,"
 #      error "CMPI_PLATFORM_OS400_ISERIES_IBM, CMPI_PLATFORM_DARWIN_PPC_GNU,"
        ^
sfcUtil/cmpi/cmpipl.h:42:6: error: #error "CMPI_PLATFORM_VMS_ALPHA_DECCXX, CMPI_PLATFORM_VMS_IA64_DECCXX"
 #    error "CMPI_PLATFORM_VMS_ALPHA_DECCXX, CMPI_PLATFORM_VMS_IA64_DECCXX"
      ^
Makefile:480: recipe for target 'utilTypeCk.lo' failed
make[2]: *** [utilTypeCk.lo] Error 1
make[2]: Leaving directory '/home/pi/Downloads/sblim-sfcCommon-1.0.1_old'
Makefile:522: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pi/Downloads/sblim-sfcCommon-1.0.1_old'
Makefile:321: recipe for target 'all' failed
make: *** [all] Error 2

>>>>>

But if I see the config.log file (after doing ./configure initially) shows "SBLIM_CMPI_PLATFORM='-D CMPI_PLATFORM_LINUX_GENERIC_GNU'" which according to me should mean the platform is set to "CMPI_PLATFORM_LINUX_GENERIC_GNU".
Then I am not sure why I am receiving the error!!
I there a way to fix it?

**Comment by zaneb** [comment]
I'm not the maintainer of this project, I just happen to have forked it once (in 2012).
